version: '3.5'
services:
  borgmatic:
    image: nickadam/borgmatic:1.0
    build: .
    environment:
      BORGMATIC_CONFIG: |
        location:
            source_directories:
            - /data
            repositories:
            - /backup
            one_file_system: true
        storage:
          compression: lz4
          archive_name_format: 'backup-{now}'
          unknown_unencrypted_repo_access_is_ok: true
        retention:
            keep_daily: 14
            prefix: 'backup-'
      BORGMATIC_CRON: |
        0 3 * * * PATH=$$PATH:/usr/bin:/usr/local/bin /usr/bin/borgmatic --syslog-verbosity 1
    volumes:
    - type: volume
      source: data
      target: /data
    - type: volume
      source: backup
      target: /backup
volumes:
  data:
  backup:
